name: ghas-alert-data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
jobs:
  get-data:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Get GHAS Alerts
      uses: expert-services/ghas-alerts@main
      with:
        github_token: ${{ secrets.GHAS_ALERT_TOKEN }}
        github_orgs: expert-services
        