name: ghas-alert-data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5,6 * * *'
jobs:
  get-data:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Execute script
      env:
        GITHUB_TOKEN: ${{ secrets.GHAS_ALERT_TOKEN }}
      run: |
        ./Get-GHASAlerts.ps1 -orgs @('OctoDemo')
      shell: pwsh
    - name: Upload artifact  
      uses: actions/upload-artifact@v3
      with:
        name: ghas-alert-data
        path: ghas_alerts/